### ISSUE TITLE
Not working in safari

### ISSUE THREAD

**Issue by vikasgudi** [gridcellcoder/cloud-speech-and-vision-demos#2]
Hi,

I am trying to implement the speech to text in my project. It is working fine in the chrome. But it is throwing the error in the safari browser. Can any one please help me regarding this?

Below is the error which I got when I run the code in safari browser:

`Error: Uncaught (in promise): TypeError: undefined is not a constructor (near '...n.SpeechRecognition)();...') createEngine@http://localhost:9000/main.bundle.js:1387:35 create@http://localhost:9000/main.bundle.js:1368:40 WebSpeechService@http://localhost:9000/main.bundle.js:1332:20 _createClass@http://localhost:9000/vendor.bundle.js:90602:28 _createProviderInstance$1@http://localhost:9000/vendor.bundle.js:90576:38 resolveNgModuleDep@http://localhost:9000/vendor.bundle.js:90561:42 createClass@http://localhost:9000/vendor.bundle.js:91993:42 createDirectiveInstance@http://localhost:9000/vendor.bundle.js:91824:48 createViewNodes@http://localhost:9000/vendor.bundle.js:93265:76 createRootView@http://localhost:9000/vendor.bundle.js:93155:20 callWithDebugContext@http://localhost:9000/vendor.bundle.js:94540:47 create@http://localhost:9000/vendor.bundle.js:90934:60 createComponent@http://localhost:9000/vendor.bundle.js:91132:68 activateWith@http://localhost:9000/vendor.bundle.js:138502:55 activateRoutes@http://localhost:9000/vendor.bundle.js:137633:52 http://localhost:9000/vendor.bundle.js:137584:72 forEach@[native code] activateChildRoutes@http://localhost:9000/vendor.bundle.js:137584:36 activate@http://localhost:9000/vendor.bundle.js:137477:33 http://localhost:9000/vendor.bundle.js:137054:30 http://localhost:9000/vendor.bundle.js:11359:25 __tryOrSetError@http://localhost:9000/vendor.bundle.js:12376:20 next@http://localhost:9000/vendor.bundle.js:12316:42 _next@http://localhost:9000/vendor.bundle.js:12254:30 next@http://localhost:9000/vendor.bundle.js:12218:23 _next@http://localhost:9000/vendor.bundle.js:28124:30 next@http://localhost:9000/vendor.bundle.js:12218:23 notifyNext@http://localhost:9000/vendor.bundle.js:28624:34 _next@http://localhost:9000/vendor.bundle.js:10980:31 next@http://localhost:9000/vendor.bundle.js:12218:23 _next@http://localhost:9000/vendor.bundle.js:28124:30 next@http://localhost:9000/vendor.bundle.js:12218:23 _subscribe@http://localhost:9000/vendor.bundle.js:16958:28 _trySubscribe@http://localhost:9000/vendor.bundle.js:11306:35 subscribe@http://localhost:9000/vendor.bundle.js:11294:106 subscribe@http://localhost:9000/vendor.bundle.js:11291:26 _innerSub@http://localhost:9000/vendor.bundle.js:28611:55 _tryNext@http://localhost:9000/vendor.bundle.js:28608:23 _next@http://localhost:9000/vendor.bundle.js:28591:26 next@http://localhost:9000/vendor.bundle.js:12218:23 notifyNext@http://localhost:9000/vendor.bundle.js:28624:34 _next@http://localhost:9000/vendor.bundle.js:10980:31 next@http://localhost:9000/vendor.bundle.js:12218:23 _next@http://localhost:9000/vendor.bundle.js:28124:30 next@http://localhost:9000/vendor.bundle.js:12218:23 _complete@http://localhost:9000/vendor.bundle.js:31783:33 complete@http://localhost:9000/vendor.bundle.js:12243:27 _complete@http://localhost:9000/vendor.bundle.js:12261:34 complete@http://localhost:9000/vendor.bundle.js:12243:27 _complete@http://localhost:9000/vendor.bundle.js:28616:38 complete@http://localhost:9000/vendor.bundle.js:12243:27 _subscribe@http://localhost:9000/vendor.bundle.js:14348:32 _trySubscribe@http://localhost:9000/vendor.bundle.js:11306:35 subscribe@http://localhost:9000/vendor.bundle.js:11294:106 subscribe@http://localhost:9000/vendor.bundle.js:11291:26 subscribe@http://localhost:9000/vendor.bundle.js:11291:26 subscribe@http://localhost:9000/vendor.bundle.js:11291:26 subscribe@http://localhost:9000/vendor.bundle.js:11291:26 _innerSub@http://localhost:9000/vendor.bundle.js:28611:55 _tryNext@http://localhost:9000/vendor.bundle.js:28608:23 _next@http://localhost:9000/vendor.bundle.js:28591:26 next@http://localhost:9000/vendor.bundle.js:12218:23 notifyNext@http://localhost:9000/vendor.bundle.js:28624:34 _next@http://localhost:9000/vendor.bundle.js:10980:31 next@http://localhost:9000/vendor.bundle.js:12218:23 _next@http://localhost:9000/vendor.bundle.js:28124:30 next@http://localhost:9000/vendor.bundle.js:12218:23 notifyNext@http://localhost:9000/vendor.bundle.js:28624:34 _next@http://localhost:9000/vendor.bundle.js:10980:31 next@http://localhost:9000/vendor.bundle.js:12218:23 notifyComplete@http://localhost:9000/vendor.bundle.js:26633:30 _complete@http://localhost:9000/vendor.bundle.js:26650:28 complete@http://localhost:9000/vendor.bundle.js:12243:27 _complete@http://localhost:9000/vendor.bundle.js:28616:38 complete@http://localhost:9000/vendor.bundle.js:12243:27 _subscribe@http://localhost:9000/vendor.bundle.js:14348:32 _trySubscribe@http://localhost:9000/vendor.bundle.js:11306:35 subscribe@http://localhost:9000/vendor.bundle.js:11294:106 subscribe@http://localhost:9000/vendor.bundle.js:11291:26 subscribe@http://localhost:9000/vendor.bundle.js:11291:26 _innerSub@http://localhost:9000/vendor.bundle.js:28611:55 _tryNext@http://localhost:9000/vendor.bundle.js:28608:23 _next@http://localhost:9000/vendor.bundle.js:28591:26 next@http://localhost:9000/vendor.bundle.js:12218:23 notifyComplete@http://localhost:9000/vendor.bundle.js:26633:30 _complete@http://localhost:9000/vendor.bundle.js:26650:28 complete@http://localhost:9000/vendor.bundle.js:12243:27 _complete@http://localhost:9000/vendor.bundle.js:28616:38 complete@http://localhost:9000/vendor.bundle.js:12243:27 _subscribe@http://localhost:9000/vendor.bundle.js:14348:32 _trySubscribe@http://localhost:9000/vendor.bundle.js:11306:35 subscribe@http://localhost:9000/vendor.bundle.js:11294:106 subscribe@http://localhost:9000/vendor.bundle.js:11291:26 subscribe@http://localhost:9000/vendor.bundle.js:11291:26 subscribe@http://localhost:9000/vendor.bundle.js:11291:26 subscribe@http://localhost:9000/vendor.bundle.js:11291:26 _innerSub@http://localhost:9000/vendor.bundle.js:28611:55 _tryNext@http://localhost:9000/vendor.bundle.js:28608:23 _next@http://localhost:9000/vendor.bundle.js:28591:26 next@http://localhost:9000/vendor.bundle.js:12218:23
resolvePromise — zone.js:814
resolvePromise — zone.js:771
(anonymous function) — zone.js:873
onInvokeTask — core.es5.js:3881
runTask — zone.js:188
drainMicroTaskQueue — zone.js:595
promiseReactionJob
defaultErrorLogger — core.es5.js:1020
handleError — core.es5.js:1080
next — core.es5.js:4503:118
(anonymous function) — core.es5.js:3635
__tryOrUnsub — Subscriber.js:242
next — Subscriber.js:189
_next — Subscriber.js:129
next — Subscriber.js:93
next — Subject.js:55
emit — core.es5.js:3621
run — zone.js:138
onHandleError — core.es5.js:3912
runGuarded — zone.js:154
_loop_1 — zone.js:677
microtaskDrainDone — zone.js:686
drainMicroTaskQueue — zone.js:602
promiseReactionJob
log — client:45`

**Comment by gridcellcoder** [comment]
Unfortunately this implementation does not work with Safari.
